<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * An uploaded image: metadata here, bytes on the configured filesystem disk.
 *
 *   { id: "6a61bd5045dab5140eaec7d5", contentType: "image/jpeg",
 *     path: "media/6a61bd5045dab5140eaec7d5.jpg", size, disk,
 *     createdAt, updatedAt }
 *
 * The key is a 24-character hex string rather than an auto-increment, because
 * content records address images by "/api/media/<id>" and those ids are part of
 * the stored data. App\Services\MediaService generates ids in the same format
 * for new uploads, so old and new rows are indistinguishable.
 */
class Media extends Model
{
    protected $table = 'media';

    /** Ids are generated by MediaService, not by MySQL. */
    public $incrementing = false;

    protected $keyType = 'string';

    public const CREATED_AT = 'createdAt';

    public const UPDATED_AT = 'updatedAt';

    protected $fillable = ['id', 'contentType', 'path', 'size', 'disk'];

    protected function casts(): array
    {
        return [
            'size' => 'integer',
        ];
    }
}
